### ISSUE TITLE
核弹消失，抛射体不准确

### ISSUE THREAD

**Issue by Daiki9527** [ChrisLv-CN/YRDynamicPatcher-Kratos#1]
如视频所示：https://user-images.githubusercontent.com/97156139/156973024-6cc43779-2030-41b6-a4f8-4da3ef7388f5.mp4
或者如图所示：![edit 2022-03-07 01-31-34](https://user-images.githubusercontent.com/97156139/156977459-b44f5890-d13a-41c6-9123-7be4e8f5907f.gif)
### 抛射体Arcing用上Phobos的Gravity=0和Gravity.HeightFix=true后会这样：
![desktop 2022-03-07 13-51-21](https://user-images.githubusercontent.com/97156139/156977379-f9c5a2a4-8d66-4ca6-8f10-6b13c038cebc.gif)
![desktop 2022-03-07 13-53-05](https://user-images.githubusercontent.com/97156139/156977432-34e60f5f-f784-418d-a5a5-7c4083bdd9ba.gif)

**Comment by ChrisLv-CN** [comment]
1、核弹抛射体因为[NukeCarrier]的damage=0所以被判定为死亡，只需要加上Damage=1就可以解决。下个版本会修复。
2、Arcing在Kratos是修改了抛物线的弹道计算公式来获得精准的命中效果，Phobos的修改重力则是修改了抛射体的基础速度，这会让公式的计算的结果错误，解法只能是二选一，想要实现直线弹道用ROT=1的导弹。

**Comment by ChrisLv-CN** [comment]
Build 6.21 已经修复了这个问题，现在Damage=0的抛射体不会被判定为死亡，核弹可以正常显示。通过给Arcing抛射体加上AdvancedBallistics=no来关闭高级弹道，这样就可以使用Phobos的修改重力的逻辑了。
