### ISSUE TITLE
LINUX WINE/PROTON Issue when Testing Tiberium Wars Ionshock For Yuris Revenge

### ISSUE THREAD

**Issue by Tribalwarfare** [ChrisLv-CN/YRDynamicPatcher-Kratos#5]
Issue: Launch Game using WINE 7.X on Manjaro Linux.
.Net 4.8 and VCRUN components installed in Prefix.

Game Client executed Syringe.exe process and DynamicPatcher process. gamemd.exe window opens but eventually errors and produces logs.

Please see attached error logs to please kindly assist with troubleshooting Linux Wine.

[client.log](https://github.com/ChrisLv-CN/YRDynamicPatcher-Kratos/files/9199954/client.log)
[except.txt](https://github.com/ChrisLv-CN/YRDynamicPatcher-Kratos/files/9199920/except.txt)
[syringe.log](https://github.com/ChrisLv-CN/YRDynamicPatcher-Kratos/files/9199921/syringe.log)
[debug.log](https://github.com/ChrisLv-CN/YRDynamicPatcher-Kratos/files/9199922/debug.log)
[patcher.log](https://github.com/ChrisLv-CN/YRDynamicPatcher-Kratos/files/9199928/patcher.log)

Thank you for your kind assistance.
AG

**Comment by ChrisLv-CN** [comment]
I haven't no idea about how to use linux play this game.

**Comment by Tribalwarfare** [comment]
> 

Thanks for the reply, have the logs been of any help?
Is there anything I can do send info?

**Comment by Tribalwarfare** [comment]
Please close the issue. I was able to track down the root cause.
Many Thanks :)
